CREATE TABLE Fornecedor (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    codigo CHAR(8) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    cnpj CHAR(14) NOT NULL UNIQUE,
    email VARCHAR(60) NOT NULL UNIQUE,
    telefone CHAR(11) NOT NULL
)ENGINE=INNODB;
